[tool.poetry]
name = "chess"
version = "0.2.0"
description = ""
authors = ["Robin Chalas"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11.6"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
